######################################################
# pipeline_MR configuration file
######################################################

######################################################
# Pipeline general options:
general:
# Specify the location of the scripts for this project. Needs to be set.
    project_scripts_dir: 

# Specify the python executable, this is if running on a Mac and using matplotlib (which needs pythonw):
    py_exec:
#either "python" or "pythonw"

# scratchdir for data not to be backed up
    scratchdir:
    #/tmp

# a version string
    version:

# Pipeline database options:
database:
    url: sqlite:///./csvdb
######################################################

######################################################
# Programme specific options (tools called from this pipeline)

# See run_2SMR.R for options
# run_2SMR.R --help
# https://github.com/AntonioJBT/pipeline_MR/blob/master/scripts/run_2SMR.R
# --exposure and --outcome are already provided in the pipeline
# if using -O files will start as eg bmi_on_nameofoutcomefile
<<<<<<< HEAD
run_2SMR: -O pqtl --outcome-type 'quant' --mr-methods 'main' --stop-clumping 
=======
run_2SMR: -O ville_pqtl --outcome-type 'quant' --stop-clumping --mr-methods 'main'
>>>>>>> e2b722bf1d2ab5ccca485c52005d1ac44b1d81ce

######################################################
